-- Create Group Data table
CREATE TABLE public."Group Data" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  media_type text,
  media_group text,
  media_name text,
  amount numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE public."Group Data" ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access
CREATE POLICY "Allow public read access to Group Data"
ON public."Group Data"
FOR SELECT
USING (true);