// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfipxohkdrcxtvsqnbin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmaXB4b2hrZHJjeHR2c3FuYmluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNjE4MDYsImV4cCI6MjA1OTkzNzgwNn0.ZR_61IjkgnDi5_cYjZk5YpuaUGmN7kB461YSWJNKEbo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);